
CREATE DATABASE micro_mail;
CREATE DATABASE micro_user;

\connect micro_user

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    nome VARCHAR(255),
    status VARCHAR(255),
    PRIMARY KEY (id)
);
