server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: mail-service
          uri: http://mail-service:8081
          predicates:
            - Path=/mail/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1